=== apache/cayenne/cayenne/src/main/resources/org/apache/cayenne/schema/12/modelMap.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  ~   Licensed to the Apache Software Foundation (ASF) under one
  ~  or more contributor license agreements.  See the NOTICE file
  ~  distributed with this work for additional information
  ~  regarding copyright ownership.  The ASF licenses this file
  ~  to you under the Apache License, Version 2.0 (the
  ~  "License"); you may not use this file except in compliance
  ~  with the License.  You may obtain a copy of the License at
  ~
  ~    https://www.apache.org/licenses/LICENSE-2.0
  ~
  ~  Unless required by applicable law or agreed to in writing,
  ~  software distributed under the License is distributed on an
  ~  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
  ~  KIND, either express or implied.  See the License for the
  ~  specific language governing permissions and limitations
  ~  under the License.
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->

<!--
	Cayenne entity map schema
	Defines format of Cayenne DataMap XML files (*.map.xml).  DataMap files contain
	the metadata needed for Cayenne object-relational features. Multiple DataMaps
	are usually combined in one shared namespace, so the elements of the DataMap
	may reference objects from other DataMaps.
-->
<xs:schema targetNamespace="http://cayenne.apache.org/schema/12/modelMap"
	xmlns:cay="http://cayenne.apache.org/schema/12/modelMap"
	xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" version="12">
	<xs:element name="data-map">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="cay:property"/>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="cay:embeddable"/>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="cay:procedure"/>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="cay:db-entity"/>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="cay:obj-entity"/>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="cay:db-relationship"/>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="cay:obj-relationship"/>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="cay:query"/>
				<xs:any minOccurs="0" maxOccurs="unbounded" namespace="##other" processContents="lax"/>
			</xs:sequence>
			<xs:attribute name="project-version" use="required" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="db-entity">
		<xs:complexType>
			<xs:sequence>
				<xs:element maxOccurs="unbounded" ref="cay:db-attribute"/>
				<xs:element minOccurs="0" ref="cay:db-key-generator"/>

				<!-- Qualifier for DB Entity -->
				<xs:element minOccurs="0" ref="cay:qualifier"/>

				<xs:any minOccurs="0" maxOccurs="unbounded" namespace="##other" processContents="lax"/>
			</xs:sequence>
			<xs:attribute name="name" use="required" type="xs:string"/>
			<xs:attribute name="schema" type="xs:string"/>
			<xs:attribute name="catalog" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="db-attribute">
		<xs:annotation>
			<xs:documentation>A database column.</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:any minOccurs="0" maxOccurs="unbounded" namespace="##other" processContents="lax"/>
			</xs:sequence>
			<xs:attribute name="isMandatory" type="xs:boolean"/>
			<xs:attribute name="isPrimaryKey" type="xs:boolean">
				<xs:annotation>
					<xs:documentation>If true, the value of attribute is unique and used as a primary key identifier.</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="isGenerated" type="xs:boolean"/>
			<xs:attribute name="length" type="xs:integer"/>
			<xs:attribute name="name" use="required" type="xs:string"/>
			<xs:attribute name="scale" type="xs:integer"/>
			<xs:attribute name="type" use="required" type="xs:string"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="obj-entity">
		<xs:annotation>
			<xs:documentation>A persistent Java class managed by Cayenne.</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" ref="cay:qualifier"/>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="cay:embedded-attribute"/>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="cay:obj-attribute"/>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="cay:attribute-override"/>

				<!--  Callbacks -->
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="cay:post-add"/>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="cay:pre-persist"/>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="cay:post-persist"/>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="cay:pre-update"/>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="cay:post-update"/>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="cay:pre-remove"/>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="cay:post-remove"/>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="cay:post-load"/>

				<xs:any minOccurs="0" maxOccurs="unbounded" namespace="##other" processContents="lax"/>
			</xs:sequence>
			<xs:attribute name="className" type="xs:string"/>
			<xs:attribute name="abstract" type="xs:boolean"/>
			<xs:attribute name="readOnly" type="xs:boolean"/>
			<xs:attribute name="dbEntityName" type="xs:string"/>
			<xs:attribute name="lock-type" type="xs:string"/>
			<xs:attribute name="name" use="required" type="xs:string"/>
			<xs:attribute name="superClassName" type="xs:string"/>
			<xs:attribute name="superEntityName" type="xs:string"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="qualifier" type="xs:string"/>

	<xs:element name="obj-attribute">
		<xs:complexType>
			<xs:sequence>
				<xs:any minOccurs="0" maxOccurs="unbounded" namespace="##other" processContents="lax"/>
			</xs:sequence>
			<xs:attribute name="db-attribute-path" type="xs:string"/>
			<xs:attribute name="lock" type="xs:boolean"/>
			<xs:attribute name="name" use="required" type="xs:string"/>
			<xs:attribute name="type" use="required" type="xs:string"/>
			<xs:attribute name="lazy" type="xs:boolean"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="attribute-override">
		<xs:complexType>
			<xs:attribute name="db-attribute-path" type="xs:string"/>
			<xs:attribute name="lock" type="xs:boolean"/>
			<xs:attribute name="name" type="xs:string"/>
			<xs:attribute name="type" type="xs:string"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="db-relationship">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="unbounded" ref="cay:db-attribute-pair"/>
				<xs:any minOccurs="0" maxOccurs="unbounded" namespace="##other" processContents="lax"/>
			</xs:sequence>
			<xs:attribute name="name" use="required" type="xs:string"/>
			<xs:attribute name="source" use="required" type="xs:string"/>
			<xs:attribute name="target" use="required" type="xs:string"/>
			<xs:attribute name="toDependentPK" type="xs:boolean"/>
			<xs:attribute name="toMany" type="xs:boolean"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="db-attribute-pair">
		<xs:complexType>
			<xs:attribute name="source" use="required" type="xs:string"/>
			<xs:attribute name="target" use="required" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="obj-relationship">
		<xs:complexType>
			<xs:sequence>
				<xs:any minOccurs="0" maxOccurs="unbounded" namespace="##other" processContents="lax"/>
			</xs:sequence>
			<xs:attribute name="db-relationship-path" use="required" type="xs:string"/>
			<xs:attribute name="deleteRule" type="xs:string"/>
			<xs:attribute name="lock" type="xs:boolean"/>
			<xs:attribute name="name" use="required" type="xs:string"/>
			<xs:attribute name="source" use="required" type="xs:string"/>
			<xs:attribute name="target" use="required" type="xs:string"/>
			<xs:attribute name="collection-type" type="xs:string"/>
			<xs:attribute name="map-key" type="xs:string"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="query">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="cay:property"/>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="cay:sql"/>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="cay:ejbql"/>
				<xs:element name="qualifier" minOccurs="0" maxOccurs="unbounded" type="xs:string"/>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="cay:ordering"/>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="cay:prefetch"/>
				<xs:any minOccurs="0" maxOccurs="unbounded" namespace="##other" processContents="lax"/>
			</xs:sequence>
			<xs:attribute name="type" use="required" type="xs:string"/>
			<xs:attribute name="name" use="required" type="xs:string"/>
			<xs:attribute name="root" type="xs:string"/>
			<xs:attribute name="root-name" type="xs:string"/>
			<xs:attribute name="result-entity" type="xs:string"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="ordering">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="descending" type="xs:boolean"/>
					<xs:attribute name="ignore-case" type="xs:boolean"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="prefetch">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="type" type="xs:string"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="sql">
		<xs:annotation>
			<xs:documentation>Defines arbitrary SQL statement. Note that SQL statement can be customized for different SQL dialects per DbAdapter class. If no adapter-specific statement is found, the one with no adapter label is used by default.</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="adapter-class" type="xs:string"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="ejbql" type="xs:string"/>

	<xs:element name="property">
		<xs:annotation>
			<xs:documentation>A generic property used by other elements.</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:attribute name="name" use="required" type="xs:string"/>
			<xs:attribute name="value" use="required" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="embeddable">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="embeddable-attribute" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:attribute name="name" use="required" type="xs:string"/>
						<xs:attribute name="type" use="required" type="xs:string"/>
						<xs:attribute name="db-attribute-name" use="required" type="xs:string"/>
					</xs:complexType>
				</xs:element>
				<xs:any minOccurs="0" maxOccurs="unbounded" namespace="##other" processContents="lax"/>
			</xs:sequence>
			<xs:attribute name="className" use="required" type="xs:string"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="embedded-attribute">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" maxOccurs="unbounded"
					ref="cay:embeddable-attribute-override"/>
			</xs:sequence>
			<xs:attribute name="type" use="required" type="xs:string"/>
			<xs:attribute name="name" use="required" type="xs:string"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="embeddable-attribute-override">
		<xs:complexType>
			<xs:attribute name="db-attribute-path" use="required" type="xs:string"/>
			<xs:attribute name="name" use="required" type="xs:string"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="procedure">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" maxOccurs="unbounded" name="procedure-parameter">
					<xs:complexType>
						<xs:attribute name="name" use="required" type="xs:string"/>
						<xs:attribute name="type" use="required" type="xs:string"/>
						<xs:attribute name="length" type="xs:integer"/>
						<xs:attribute name="direction" use="required" type="xs:string"/>
					</xs:complexType>
				</xs:element>
				<xs:any minOccurs="0" maxOccurs="unbounded" namespace="##other" processContents="lax"/>
			</xs:sequence>
			<xs:attribute name="name" use="required" type="xs:string"/>
			<xs:attribute name="schema" type="xs:string"/>
			<xs:attribute name="catalog" type="xs:string"/>
			<xs:attribute name="returningValue" type="xs:boolean"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="pre-update">
		<xs:complexType>
			<xs:attribute name="method-name" use="required" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="post-persist">
		<xs:complexType>
			<xs:attribute name="method-name" use="required" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="post-update">
		<xs:complexType>
			<xs:attribute name="method-name" use="required" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="post-add">
		<xs:complexType>
			<xs:attribute name="method-name" use="required" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="pre-persist">
		<xs:complexType>
			<xs:attribute name="method-name" use="required" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="post-remove">
		<xs:complexType>
			<xs:attribute name="method-name" use="required" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="post-load">
		<xs:complexType>
			<xs:attribute name="method-name" use="required" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="pre-remove">
		<xs:complexType>
			<xs:attribute name="method-name" use="required" type="xs:string"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="db-key-generator">
		<xs:annotation>
			<xs:documentation>Used to install the Automatic Sequence/Key Generation facility for db-entity. This feature is intended for use with simple (non-compound) integral primary keys.</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="db-generator-type" type="xs:string">
					<xs:annotation>
						<xs:documentation>Specifies the Key Generation Method that will be employed
      'ORACLE'               - use Oracle's SEQUENCE
      'NAMED_SEQUENCE_TABLE' - use USER designated SEQUENCE TABLE. User specifies the name of a DBMS Table with the schema (sequence INT) which will be used to hold sequence values (not supported yet)</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element minOccurs="0" name="db-generator-name" type="xs:string">
					<xs:annotation>
						<xs:documentation>For db-generator-type ORACLE this is the name of the ORACLE SEQUENCE to use. The SEQUENCE is assumed to already exist in the Database.
If this is db-generator-type NAMED_SEQUENCE_TABLE Key Generation, this specifies the name of the SEQUENCE TABLE to use. The NAMED_SEQUENCE_TABLE is assumed to already exist in the database.</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element minOccurs="0" name="db-key-cache-size" type="xs:integer">
					<xs:annotation>
						<xs:documentation>Size of key cache. For db-generator-type ORACLE , this value MUST match the Oracle SEQUENCE  INCREMENT value.  If there is a mismatch between this value and the Oracle SEQUENCE INCREMENT value, then there will likely be duplicate key problems.
For db-generator-type NAMED_SEQUENCE_TABLE , this tells how many keys the Container will fetch in a single DBMS call.</xs:documentation>
					</xs:annotation>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== apache/cayenne/cayenne/src/test/resources/table-primitives.map.xml
<?xml version="1.0" encoding="utf-8"?>
<data-map xmlns="http://cayenne.apache.org/schema/11/modelMap"
	 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	 xsi:schemaLocation="http://cayenne.apache.org/schema/11/modelMap https://cayenne.apache.org/schema/11/modelMap.xsd"
	 project-version="11">
	<property name="defaultPackage" value="org.apache.cayenne.testdo.table_primitives"/>
	<db-entity name="TABLE_PRIMITIVES">
		<db-attribute name="BOOLEAN_COLUMN" type="BOOLEAN"/>
		<db-attribute name="ID" type="INTEGER" isPrimaryKey="true" isMandatory="true"/>
		<db-attribute name="INT_COLUMN" type="INTEGER"/>
	</db-entity>
	<obj-entity name="TablePrimitives" className="org.apache.cayenne.testdo.table_primitives.TablePrimitives" dbEntityName="TABLE_PRIMITIVES">
		<obj-attribute name="booleanColumn" type="boolean" db-attribute-path="BOOLEAN_COLUMN"/>
		<obj-attribute name="intColumn" type="int" db-attribute-path="INT_COLUMN"/>
	</obj-entity>
</data-map>

=== apache/cayenne/cayenne/src/test/resources/compound.map.xml
<?xml version="1.0" encoding="utf-8"?>
<data-map xmlns="http://cayenne.apache.org/schema/12/modelMap"
	 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	 xsi:schemaLocation="http://cayenne.apache.org/schema/12/modelMap https://cayenne.apache.org/schema/12/modelMap.xsd"
	 project-version="12">
	<property name="defaultPackage" value="org.apache.cayenne.testdo.compound"/>
	<property name="defaultSuperclass" value="org.apache.cayenne.GenericPersistentObject"/>
	<db-entity name="CHAR_FK_TEST">
		<db-attribute name="FK_COL" type="CHAR" length="10"/>
		<db-attribute name="NAME" type="VARCHAR" length="100"/>
		<db-attribute name="PK" type="INTEGER" isPrimaryKey="true" isMandatory="true"/>
	</db-entity>
	<db-entity name="CHAR_PK_TEST">
		<db-attribute name="OTHER_COL" type="CHAR" length="10"/>
		<db-attribute name="PK_COL" type="CHAR" isPrimaryKey="true" isMandatory="true" length="10"/>
	</db-entity>
	<db-entity name="COMPOUND_FK_TEST">
		<db-attribute name="F_KEY1" type="VARCHAR" length="20"/>
		<db-attribute name="F_KEY2" type="VARCHAR" length="20"/>
		<db-attribute name="NAME" type="VARCHAR" length="255"/>
		<db-attribute name="PKEY" type="INTEGER" isPrimaryKey="true" isMandatory="true"/>
	</db-entity>
	<db-entity name="COMPOUND_INT_PK">
		<db-attribute name="id1" type="INTEGER" isPrimaryKey="true" isMandatory="true"/>
		<db-attribute name="id2" type="INTEGER" isPrimaryKey="true" isMandatory="true"/>
		<db-attribute name="name" type="VARCHAR" length="100"/>
	</db-entity>
	<db-entity name="COMPOUND_PK_TEST">
		<db-attribute name="KEY1" type="VARCHAR" isPrimaryKey="true" isMandatory="true" length="20"/>
		<db-attribute name="KEY2" type="VARCHAR" isPrimaryKey="true" isMandatory="true" length="20"/>
		<db-attribute name="NAME" type="VARCHAR" length="255"/>
	</db-entity>
	<db-entity name="compound_order">
		<db-attribute name="info" type="VARCHAR" length="255"/>
		<db-attribute name="order_number" type="INTEGER" isPrimaryKey="true" isMandatory="true"/>
	</db-entity>
	<db-entity name="compound_order_line">
		<db-attribute name="order_line_number" type="INTEGER" isPrimaryKey="true" isMandatory="true"/>
		<db-attribute name="order_number" type="INTEGER" isPrimaryKey="true" isMandatory="true"/>
	</db-entity>
	<db-entity name="compound_order_line_info">
		<db-attribute name="info" type="VARCHAR" length="255"/>
		<db-attribute name="order_line_number" type="INTEGER" isPrimaryKey="true" isMandatory="true"/>
		<db-attribute name="order_number" type="INTEGER" isPrimaryKey="true" isMandatory="true"/>
	</db-entity>
	<obj-entity name="CharFkTestEntity" className="org.apache.cayenne.testdo.compound.CharFkTestEntity" dbEntityName="CHAR_FK_TEST">
		<obj-attribute name="name" type="java.lang.String" db-attribute-path="NAME"/>
	</obj-entity>
	<obj-entity name="CharPkTestEntity" className="org.apache.cayenne.testdo.compound.CharPkTestEntity" dbEntityName="CHAR_PK_TEST">
		<obj-attribute name="otherCol" type="java.lang.String" db-attribute-path="OTHER_COL"/>
		<obj-attribute name="pkCol" type="java.lang.String" db-attribute-path="PK_COL"/>
	</obj-entity>
	<obj-entity name="CompoundFkTestEntity" className="org.apache.cayenne.testdo.compound.CompoundFkTestEntity" dbEntityName="COMPOUND_FK_TEST">
		<obj-attribute name="name" type="java.lang.String" db-attribute-path="NAME"/>
	</obj-entity>
	<obj-entity name="CompoundIntPk" className="org.apache.cayenne.testdo.compound.CompoundIntPk" dbEntityName="COMPOUND_INT_PK">
		<obj-attribute name="id1" type="java.lang.Integer" db-attribute-path="id1"/>
		<obj-attribute name="id2" type="java.lang.Integer" db-attribute-path="id2"/>
		<obj-attribute name="name" type="java.lang.String" db-attribute-path="name"/>
	</obj-entity>
	<obj-entity name="CompoundOrder" className="org.apache.cayenne.testdo.compound.CompoundOrder" dbEntityName="compound_order" superClassName="org.apache.cayenne.GenericPersistentObject">
		<obj-attribute name="info" type="java.lang.String" db-attribute-path="info"/>
	</obj-entity>
	<obj-entity name="CompoundOrderLine" className="org.apache.cayenne.testdo.compound.CompoundOrderLine" dbEntityName="compound_order_line" superClassName="org.apache.cayenne.GenericPersistentObject">
		<obj-attribute name="lineNumber" type="int" db-attribute-path="order_line_number"/>
	</obj-entity>
	<obj-entity name="CompoundOrderLineInfo" className="org.apache.cayenne.testdo.compound.CompoundOrderLineInfo" dbEntityName="compound_order_line_info" superClassName="org.apache.cayenne.GenericPersistentObject">
		<obj-attribute name="info" type="java.lang.String" db-attribute-path="info"/>
	</obj-entity>
	<obj-entity name="CompoundPkTestEntity" className="org.apache.cayenne.testdo.compound.CompoundPkTestEntity" dbEntityName="COMPOUND_PK_TEST">
		<obj-attribute name="key1" type="java.lang.String" db-attribute-path="KEY1"/>
		<obj-attribute name="key2" type="java.lang.String" db-attribute-path="KEY2"/>
		<obj-attribute name="name" type="java.lang.String" db-attribute-path="NAME"/>
	</obj-entity>
	<db-relationship name="toCharPK" source="CHAR_FK_TEST" target="CHAR_PK_TEST">
		<db-attribute-pair source="FK_COL" target="PK_COL"/>
	</db-relationship>
	<db-relationship name="charFKs" source="CHAR_PK_TEST" target="CHAR_FK_TEST" toMany="true">
		<db-attribute-pair source="PK_COL" target="FK_COL"/>
	</db-relationship>
	<db-relationship name="toCompoundPk" source="COMPOUND_FK_TEST" target="COMPOUND_PK_TEST">
		<db-attribute-pair source="F_KEY1" target="KEY1"/>
		<db-attribute-pair source="F_KEY2" target="KEY2"/>
	</db-relationship>
	<db-relationship name="compoundFkArray" source="COMPOUND_PK_TEST" target="COMPOUND_FK_TEST" toMany="true">
		<db-attribute-pair source="KEY1" target="F_KEY1"/>
		<db-attribute-pair source="KEY2" target="F_KEY2"/>
	</db-relationship>
	<db-relationship name="lines" source="compound_order" target="compound_order_line" toDependentPK="true" toMany="true">
		<db-attribute-pair source="order_number" target="order_number"/>
	</db-relationship>
	<db-relationship name="info" source="compound_order_line" target="compound_order_line_info" toDependentPK="true">
		<db-attribute-pair source="order_number" target="order_number"/>
		<db-attribute-pair source="order_line_number" target="order_line_number"/>
	</db-relationship>
	<db-relationship name="order" source="compound_order_line" target="compound_order">
		<db-attribute-pair source="order_number" target="order_number"/>
	</db-relationship>
	<db-relationship name="line" source="compound_order_line_info" target="compound_order_line">
		<db-attribute-pair source="order_number" target="order_number"/>
		<db-attribute-pair source="order_line_number" target="order_line_number"/>
	</db-relationship>
	<obj-relationship name="toCharPK" source="CharFkTestEntity" target="CharPkTestEntity" db-relationship-path="toCharPK"/>
	<obj-relationship name="charFKs" source="CharPkTestEntity" target="CharFkTestEntity" db-relationship-path="charFKs"/>
	<obj-relationship name="toCompoundPk" source="CompoundFkTestEntity" target="CompoundPkTestEntity" db-relationship-path="toCompoundPk"/>
	<obj-relationship name="lines" source="CompoundOrder" target="CompoundOrderLine" deleteRule="Deny" db-relationship-path="lines"/>
	<obj-relationship name="info" source="CompoundOrderLine" target="CompoundOrderLineInfo" deleteRule="Nullify" db-relationship-path="info"/>
	<obj-relationship name="order" source="CompoundOrderLine" target="CompoundOrder" deleteRule="Nullify" db-relationship-path="order"/>
	<obj-relationship name="line" source="CompoundOrderLineInfo" target="CompoundOrderLine" deleteRule="Nullify" db-relationship-path="line"/>
	<obj-relationship name="compoundFkArray" source="CompoundPkTestEntity" target="CompoundFkTestEntity" db-relationship-path="compoundFkArray"/>
</data-map>

=== apache/cayenne/cayenne-server/src/test/resources/inheritance-single-table1.map.xml
<?xml version="1.0" encoding="utf-8"?>
<data-map xmlns="http://cayenne.apache.org/schema/8/modelMap"
	 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	 xsi:schemaLocation="http://cayenne.apache.org/schema/8/modelMap http://cayenne.apache.org/schema/8/modelMap.xsd"
	 project-version="8">
	<property name="defaultPackage" value="org.apache.cayenne.testdo.inheritance_flat"/>
	<db-entity name="GROUP_MEMBERS">
		<db-attribute name="group_id" type="BIGINT" isMandatory="true"/>
		<db-attribute name="id" type="BIGINT" isPrimaryKey="true" isMandatory="true"/>
		<db-attribute name="role_id" type="BIGINT" isMandatory="true"/>
	</db-entity>
	<db-entity name="GROUP_PROPERTIES">
		<db-attribute name="description" type="VARCHAR" length="100"/>
		<db-attribute name="id" type="BIGINT" isPrimaryKey="true" isMandatory="true"/>
	</db-entity>
	<db-entity name="ROLES">
		<db-attribute name="id" type="BIGINT" isPrimaryKey="true" isMandatory="true"/>
		<db-attribute name="name" type="VARCHAR" isMandatory="true" length="32"/>
		<db-attribute name="type" type="SMALLINT" isMandatory="true"/>
	</db-entity>
	<db-entity name="USER_PROPERTIES">
		<db-attribute name="id" type="BIGINT" isPrimaryKey="true" isMandatory="true"/>
		<db-attribute name="nickname" type="VARCHAR" length="32"/>
	</db-entity>
	<obj-entity name="Group" superEntityName="User" className="org.apache.cayenne.testdo.inheritance_flat.Group">
		<qualifier><![CDATA[type = 2]]></qualifier>
	</obj-entity>
	<obj-entity name="GroupProperties" className="org.apache.cayenne.testdo.inheritance_flat.GroupProperties" dbEntityName="GROUP_PROPERTIES">
		<obj-attribute name="description" type="java.lang.String" db-attribute-path="description"/>
		<obj-attribute name="id" type="java.lang.Long" db-attribute-path="id"/>
	</obj-entity>
	<obj-entity name="Role" className="org.apache.cayenne.testdo.inheritance_flat.Role" dbEntityName="ROLES">
		<qualifier><![CDATA[type = 0]]></qualifier>
		<obj-attribute name="id" type="long" db-attribute-path="id"/>
		<obj-attribute name="name" type="java.lang.String" lock="true" db-attribute-path="name"/>
		<obj-attribute name="type" type="int" db-attribute-path="type"/>
		<post-persist method-name="onPostPersist"/>
		<post-update method-name="onPostUpdate"/>
	</obj-entity>
	<obj-entity name="User" superEntityName="Role" className="org.apache.cayenne.testdo.inheritance_flat.User">
		<qualifier><![CDATA[type = 1]]></qualifier>
		<attribute-override name="id" db-attribute-path="id"/>
		<attribute-override name="name" db-attribute-path="name"/>
		<attribute-override name="type" db-attribute-path="type"/>
	</obj-entity>
	<obj-entity name="UserProperties" className="org.apache.cayenne.testdo.inheritance_flat.UserProperties" dbEntityName="USER_PROPERTIES">
		<obj-attribute name="id" type="java.lang.Long" db-attribute-path="id"/>
		<obj-attribute name="nickname" type="java.lang.String" db-attribute-path="nickname"/>
	</obj-entity>
	<db-relationship name="group" source="GROUP_MEMBERS" target="ROLES" toMany="false">
		<db-attribute-pair source="group_id" target="id"/>
	</db-relationship>
	<db-relationship name="role" source="GROUP_MEMBERS" target="ROLES" toMany="false">
		<db-attribute-pair source="role_id" target="id"/>
	</db-relationship>
	<db-relationship name="group" source="GROUP_PROPERTIES" target="ROLES" toMany="false">
		<db-attribute-pair source="id" target="id"/>
	</db-relationship>
	<db-relationship name="group_members" source="ROLES" target="GROUP_MEMBERS" toMany="true">
		<db-attribute-pair source="id" target="group_id"/>
	</db-relationship>
	<db-relationship name="group_properties" source="ROLES" target="GROUP_PROPERTIES" toDependentPK="true" toMany="false">
		<db-attribute-pair source="id" target="id"/>
	</db-relationship>
	<db-relationship name="role_groups" source="ROLES" target="GROUP_MEMBERS" toMany="true">
		<db-attribute-pair source="id" target="role_id"/>
	</db-relationship>
	<db-relationship name="user_properties" source="ROLES" target="USER_PROPERTIES" toDependentPK="true" toMany="false">
		<db-attribute-pair source="id" target="id"/>
	</db-relationship>
	<db-relationship name="user" source="USER_PROPERTIES" target="ROLES" toMany="false">
		<db-attribute-pair source="id" target="id"/>
	</db-relationship>
	<obj-relationship name="groupMembers" source="Group" target="Role" deleteRule="Nullify" db-relationship-path="group_members.role"/>
	<obj-relationship name="groupProperties" source="Group" target="GroupProperties" deleteRule="Cascade" db-relationship-path="group_properties"/>
	<obj-relationship name="group" source="GroupProperties" target="Group" deleteRule="Nullify" db-relationship-path="group"/>
	<obj-relationship name="roleGroups" source="Role" target="Group" deleteRule="Nullify" db-relationship-path="role_groups.group"/>
	<obj-relationship name="userProperties" source="User" target="UserProperties" deleteRule="Cascade" db-relationship-path="user_properties"/>
	<obj-relationship name="user" source="UserProperties" target="User" deleteRule="Nullify" db-relationship-path="user"/>
</data-map>
