=== apache/cayenne/cayenne/src/main/resources/org/apache/cayenne/schema/12/modelMap.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  ~   Licensed to the Apache Software Foundation (ASF) under one
  ~  or more contributor license agreements.  See the NOTICE file
  ~  distributed with this work for additional information
  ~  regarding copyright ownership.  The ASF licenses this file
  ~  to you under the Apache License, Version 2.0 (the
  ~  "License"); you may not use this file except in compliance
  ~  with the License.  You may obtain a copy of the License at
  ~
  ~    https://www.apache.org/licenses/LICENSE-2.0
  ~
  ~  Unless required by applicable law or agreed to in writing,
  ~  software distributed under the License is distributed on an
  ~  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
  ~  KIND, either express or implied.  See the License for the
  ~  specific language governing permissions and limitations
  ~  under the License.
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->

<!--
	Cayenne entity map schema
	Defines format of Cayenne DataMap XML files (*.map.xml).  DataMap files contain
	the metadata needed for Cayenne object-relational features. Multiple DataMaps
	are usually combined in one shared namespace, so the elements of the DataMap
	may reference objects from other DataMaps.
-->
<xs:schema targetNamespace="http://cayenne.apache.org/schema/12/modelMap"
	xmlns:cay="http://cayenne.apache.org/schema/12/modelMap"
	xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" version="12">
	<xs:element name="data-map">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="cay:property"/>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="cay:embeddable"/>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="cay:procedure"/>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="cay:db-entity"/>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="cay:obj-entity"/>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="cay:db-relationship"/>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="cay:obj-relationship"/>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="cay:query"/>
				<xs:any minOccurs="0" maxOccurs="unbounded" namespace="##other" processContents="lax"/>
			</xs:sequence>
			<xs:attribute name="project-version" use="required" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="db-entity">
		<xs:complexType>
			<xs:sequence>
				<xs:element maxOccurs="unbounded" ref="cay:db-attribute"/>
				<xs:element minOccurs="0" ref="cay:db-key-generator"/>

				<!-- Qualifier for DB Entity -->
				<xs:element minOccurs="0" ref="cay:qualifier"/>

				<xs:any minOccurs="0" maxOccurs="unbounded" namespace="##other" processContents="lax"/>
			</xs:sequence>
			<xs:attribute name="name" use="required" type="xs:string"/>
			<xs:attribute name="schema" type="xs:string"/>
			<xs:attribute name="catalog" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="db-attribute">
		<xs:annotation>
			<xs:documentation>A database column.</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:any minOccurs="0" maxOccurs="unbounded" namespace="##other" processContents="lax"/>
			</xs:sequence>
			<xs:attribute name="isMandatory" type="xs:boolean"/>
			<xs:attribute name="isPrimaryKey" type="xs:boolean">
				<xs:annotation>
					<xs:documentation>If true, the value of attribute is unique and used as a primary key identifier.</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="isGenerated" type="xs:boolean"/>
			<xs:attribute name="length" type="xs:integer"/>
			<xs:attribute name="name" use="required" type="xs:string"/>
			<xs:attribute name="scale" type="xs:integer"/>
			<xs:attribute name="type" use="required" type="xs:string"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="obj-entity">
		<xs:annotation>
			<xs:documentation>A persistent Java class managed by Cayenne.</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" ref="cay:qualifier"/>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="cay:embedded-attribute"/>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="cay:obj-attribute"/>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="cay:attribute-override"/>

				<!--  Callbacks -->
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="cay:post-add"/>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="cay:pre-persist"/>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="cay:post-persist"/>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="cay:pre-update"/>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="cay:post-update"/>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="cay:pre-remove"/>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="cay:post-remove"/>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="cay:post-load"/>

				<xs:any minOccurs="0" maxOccurs="unbounded" namespace="##other" processContents="lax"/>
			</xs:sequence>
			<xs:attribute name="className" type="xs:string"/>
			<xs:attribute name="abstract" type="xs:boolean"/>
			<xs:attribute name="readOnly" type="xs:boolean"/>
			<xs:attribute name="dbEntityName" type="xs:string"/>
			<xs:attribute name="lock-type" type="xs:string"/>
			<xs:attribute name="name" use="required" type="xs:string"/>
			<xs:attribute name="superClassName" type="xs:string"/>
			<xs:attribute name="superEntityName" type="xs:string"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="qualifier" type="xs:string"/>

	<xs:element name="obj-attribute">
		<xs:complexType>
			<xs:sequence>
				<xs:any minOccurs="0" maxOccurs="unbounded" namespace="##other" processContents="lax"/>
			</xs:sequence>
			<xs:attribute name="db-attribute-path" type="xs:string"/>
			<xs:attribute name="lock" type="xs:boolean"/>
			<xs:attribute name="name" use="required" type="xs:string"/>
			<xs:attribute name="type" use="required" type="xs:string"/>
			<xs:attribute name="lazy" type="xs:boolean"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="attribute-override">
		<xs:complexType>
			<xs:attribute name="db-attribute-path" type="xs:string"/>
			<xs:attribute name="lock" type="xs:boolean"/>
			<xs:attribute name="name" type="xs:string"/>
			<xs:attribute name="type" type="xs:string"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="db-relationship">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="unbounded" ref="cay:db-attribute-pair"/>
				<xs:any minOccurs="0" maxOccurs="unbounded" namespace="##other" processContents="lax"/>
			</xs:sequence>
			<xs:attribute name="name" use="required" type="xs:string"/>
			<xs:attribute name="source" use="required" type="xs:string"/>
			<xs:attribute name="target" use="required" type="xs:string"/>
			<xs:attribute name="toDependentPK" type="xs:boolean"/>
			<xs:attribute name="toMany" type="xs:boolean"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="db-attribute-pair">
		<xs:complexType>
			<xs:attribute name="source" use="required" type="xs:string"/>
			<xs:attribute name="target" use="required" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="obj-relationship">
		<xs:complexType>
			<xs:sequence>
				<xs:any minOccurs="0" maxOccurs="unbounded" namespace="##other" processContents="lax"/>
			</xs:sequence>
			<xs:attribute name="db-relationship-path" use="required" type="xs:string"/>
			<xs:attribute name="deleteRule" type="xs:string"/>
			<xs:attribute name="lock" type="xs:boolean"/>
			<xs:attribute name="name" use="required" type="xs:string"/>
			<xs:attribute name="source" use="required" type="xs:string"/>
			<xs:attribute name="target" use="required" type="xs:string"/>
			<xs:attribute name="collection-type" type="xs:string"/>
			<xs:attribute name="map-key" type="xs:string"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="query">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="cay:property"/>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="cay:sql"/>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="cay:ejbql"/>
				<xs:element name="qualifier" minOccurs="0" maxOccurs="unbounded" type="xs:string"/>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="cay:ordering"/>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="cay:prefetch"/>
				<xs:any minOccurs="0" maxOccurs="unbounded" namespace="##other" processContents="lax"/>
			</xs:sequence>
			<xs:attribute name="type" use="required" type="xs:string"/>
			<xs:attribute name="name" use="required" type="xs:string"/>
			<xs:attribute name="root" type="xs:string"/>
			<xs:attribute name="root-name" type="xs:string"/>
			<xs:attribute name="result-entity" type="xs:string"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="ordering">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="descending" type="xs:boolean"/>
					<xs:attribute name="ignore-case" type="xs:boolean"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="prefetch">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="type" type="xs:string"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="sql">
		<xs:annotation>
			<xs:documentation>Defines arbitrary SQL statement. Note that SQL statement can be customized for different SQL dialects per DbAdapter class. If no adapter-specific statement is found, the one with no adapter label is used by default.</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="adapter-class" type="xs:string"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="ejbql" type="xs:string"/>

	<xs:element name="property">
		<xs:annotation>
			<xs:documentation>A generic property used by other elements.</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:attribute name="name" use="required" type="xs:string"/>
			<xs:attribute name="value" use="required" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="embeddable">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="embeddable-attribute" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:attribute name="name" use="required" type="xs:string"/>
						<xs:attribute name="type" use="required" type="xs:string"/>
						<xs:attribute name="db-attribute-name" use="required" type="xs:string"/>
					</xs:complexType>
				</xs:element>
				<xs:any minOccurs="0" maxOccurs="unbounded" namespace="##other" processContents="lax"/>
			</xs:sequence>
			<xs:attribute name="className" use="required" type="xs:string"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="embedded-attribute">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" maxOccurs="unbounded"
					ref="cay:embeddable-attribute-override"/>
			</xs:sequence>
			<xs:attribute name="type" use="required" type="xs:string"/>
			<xs:attribute name="name" use="required" type="xs:string"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="embeddable-attribute-override">
		<xs:complexType>
			<xs:attribute name="db-attribute-path" use="required" type="xs:string"/>
			<xs:attribute name="name" use="required" type="xs:string"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="procedure">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" maxOccurs="unbounded" name="procedure-parameter">
					<xs:complexType>
						<xs:attribute name="name" use="required" type="xs:string"/>
						<xs:attribute name="type" use="required" type="xs:string"/>
						<xs:attribute name="length" type="xs:integer"/>
						<xs:attribute name="direction" use="required" type="xs:string"/>
					</xs:complexType>
				</xs:element>
				<xs:any minOccurs="0" maxOccurs="unbounded" namespace="##other" processContents="lax"/>
			</xs:sequence>
			<xs:attribute name="name" use="required" type="xs:string"/>
			<xs:attribute name="schema" type="xs:string"/>
			<xs:attribute name="catalog" type="xs:string"/>
			<xs:attribute name="returningValue" type="xs:boolean"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="pre-update">
		<xs:complexType>
			<xs:attribute name="method-name" use="required" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="post-persist">
		<xs:complexType>
			<xs:attribute name="method-name" use="required" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="post-update">
		<xs:complexType>
			<xs:attribute name="method-name" use="required" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="post-add">
		<xs:complexType>
			<xs:attribute name="method-name" use="required" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="pre-persist">
		<xs:complexType>
			<xs:attribute name="method-name" use="required" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="post-remove">
		<xs:complexType>
			<xs:attribute name="method-name" use="required" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="post-load">
		<xs:complexType>
			<xs:attribute name="method-name" use="required" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="pre-remove">
		<xs:complexType>
			<xs:attribute name="method-name" use="required" type="xs:string"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="db-key-generator">
		<xs:annotation>
			<xs:documentation>Used to install the Automatic Sequence/Key Generation facility for db-entity. This feature is intended for use with simple (non-compound) integral primary keys.</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="db-generator-type" type="xs:string">
					<xs:annotation>
						<xs:documentation>Specifies the Key Generation Method that will be employed
      'ORACLE'               - use Oracle's SEQUENCE
      'NAMED_SEQUENCE_TABLE' - use USER designated SEQUENCE TABLE. User specifies the name of a DBMS Table with the schema (sequence INT) which will be used to hold sequence values (not supported yet)</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element minOccurs="0" name="db-generator-name" type="xs:string">
					<xs:annotation>
						<xs:documentation>For db-generator-type ORACLE this is the name of the ORACLE SEQUENCE to use. The SEQUENCE is assumed to already exist in the Database.
If this is db-generator-type NAMED_SEQUENCE_TABLE Key Generation, this specifies the name of the SEQUENCE TABLE to use. The NAMED_SEQUENCE_TABLE is assumed to already exist in the database.</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element minOccurs="0" name="db-key-cache-size" type="xs:integer">
					<xs:annotation>
						<xs:documentation>Size of key cache. For db-generator-type ORACLE , this value MUST match the Oracle SEQUENCE  INCREMENT value.  If there is a mismatch between this value and the Oracle SEQUENCE INCREMENT value, then there will likely be duplicate key problems.
For db-generator-type NAMED_SEQUENCE_TABLE , this tells how many keys the Container will fetch in a single DBMS call.</xs:documentation>
					</xs:annotation>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== apache/cayenne/cayenne-server/src/test/resources/multi-tier.map.xml
<?xml version="1.0" encoding="utf-8"?>
<data-map xmlns="http://cayenne.apache.org/schema/8/modelMap"
	 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	 xsi:schemaLocation="http://cayenne.apache.org/schema/8/modelMap http://cayenne.apache.org/schema/8/modelMap.xsd"
	 project-version="8">
	<property name="defaultPackage" value="org.apache.cayenne.testdo.mt"/>
	<property name="clientSupported" value="true"/>
	<property name="defaultClientPackage" value="org.apache.cayenne.testdo.mt"/>
	<db-entity name="MT_JOIN45">
		<db-attribute name="TABLE4_ID" type="INTEGER" isPrimaryKey="true" isMandatory="true"/>
		<db-attribute name="TABLE5_ID" type="INTEGER" isPrimaryKey="true" isMandatory="true"/>
	</db-entity>
	<db-entity name="MT_TABLE1">
		<db-attribute name="GLOBAL_ATTRIBUTE1" type="VARCHAR" length="100"/>
		<db-attribute name="SERVER_ATTRIBUTE1" type="VARCHAR" length="100"/>
		<db-attribute name="SUBCLASS_ATTRIBUTE1" type="VARCHAR" length="100"/>
		<db-attribute name="TABLE1_ID" type="INTEGER" isPrimaryKey="true" isMandatory="true"/>
	</db-entity>
	<db-entity name="MT_TABLE2">
		<db-attribute name="GLOBAL_ATTRIBUTE" type="VARCHAR" length="100"/>
		<db-attribute name="TABLE1_ID" type="INTEGER"/>
		<db-attribute name="TABLE2_ID" type="INTEGER" isPrimaryKey="true" isMandatory="true"/>
		<db-attribute name="TABLE3_ID" type="INTEGER"/>
	</db-entity>
	<db-entity name="MT_TABLE3">
		<db-attribute name="BINARY_COLUMN" type="VARBINARY" length="100"/>
		<db-attribute name="CHAR_COLUMN" type="VARCHAR" length="100"/>
		<db-attribute name="INT_COLUMN" type="INTEGER"/>
		<db-attribute name="TABLE3_ID" type="INTEGER" isPrimaryKey="true" isMandatory="true"/>
	</db-entity>
	<db-entity name="MT_TABLE4">
		<db-attribute name="ID" type="INTEGER" isPrimaryKey="true" isMandatory="true"/>
	</db-entity>
	<db-entity name="MT_TABLE5">
		<db-attribute name="ID" type="INTEGER" isPrimaryKey="true" isMandatory="true"/>
	</db-entity>
	<obj-entity name="MtTable1" className="org.apache.cayenne.testdo.mt.MtTable1" clientClassName="org.apache.cayenne.testdo.mt.ClientMtTable1" dbEntityName="MT_TABLE1">
		<obj-attribute name="globalAttribute1" type="java.lang.String" db-attribute-path="GLOBAL_ATTRIBUTE1"/>
		<obj-attribute name="serverAttribute1" type="java.lang.String" db-attribute-path="SERVER_ATTRIBUTE1"/>
	</obj-entity>
	<obj-entity name="MtTable1Subclass1" superEntityName="MtTable1" className="org.apache.cayenne.testdo.mt.MtTable1Subclass1" clientClassName="org.apache.cayenne.testdo.mt.ClientMtTable1Subclass1">
		<qualifier><![CDATA[globalAttribute1 = "sub1"]]></qualifier>
		<obj-attribute name="subclass1Attribute1" type="java.lang.String" db-attribute-path="SUBCLASS_ATTRIBUTE1"/>
	</obj-entity>
	<obj-entity name="MtTable1Subclass2" superEntityName="MtTable1" className="org.apache.cayenne.testdo.mt.MtTable1Subclass2" clientClassName="org.apache.cayenne.testdo.mt.ClientMtTable1Subclass2">
		<qualifier><![CDATA[globalAttribute1 = "sub2"]]></qualifier>
		<obj-attribute name="subclass2Attribute1" type="java.lang.String" db-attribute-path="SUBCLASS_ATTRIBUTE1"/>
	</obj-entity>
	<obj-entity name="MtTable2" className="org.apache.cayenne.testdo.mt.MtTable2" clientClassName="org.apache.cayenne.testdo.mt.ClientMtTable2" dbEntityName="MT_TABLE2">
		<obj-attribute name="globalAttribute" type="java.lang.String" db-attribute-path="GLOBAL_ATTRIBUTE"/>
	</obj-entity>
	<obj-entity name="MtTable3" className="org.apache.cayenne.testdo.mt.MtTable3" clientClassName="org.apache.cayenne.testdo.mt.ClientMtTable3" dbEntityName="MT_TABLE3">
		<obj-attribute name="binaryColumn" type="byte[]" db-attribute-path="BINARY_COLUMN"/>
		<obj-attribute name="charColumn" type="java.lang.String" db-attribute-path="CHAR_COLUMN"/>
		<obj-attribute name="intColumn" type="java.lang.Integer" db-attribute-path="INT_COLUMN"/>
	</obj-entity>
	<obj-entity name="MtTable4" className="org.apache.cayenne.testdo.mt.MtTable4" clientClassName="org.apache.cayenne.testdo.mt.ClientMtTable4" dbEntityName="MT_TABLE4">
	</obj-entity>
	<obj-entity name="MtTable5" className="org.apache.cayenne.testdo.mt.MtTable5" clientClassName="org.apache.cayenne.testdo.mt.ClientMtTable5" dbEntityName="MT_TABLE5">
	</obj-entity>
	<db-relationship name="toTable4" source="MT_JOIN45" target="MT_TABLE4" toMany="false">
		<db-attribute-pair source="TABLE4_ID" target="ID"/>
	</db-relationship>
	<db-relationship name="toTable5" source="MT_JOIN45" target="MT_TABLE5" toMany="false">
		<db-attribute-pair source="TABLE5_ID" target="ID"/>
	</db-relationship>
	<db-relationship name="table2Array" source="MT_TABLE1" target="MT_TABLE2" toMany="true">
		<db-attribute-pair source="TABLE1_ID" target="TABLE1_ID"/>
	</db-relationship>
	<db-relationship name="table1" source="MT_TABLE2" target="MT_TABLE1" toMany="false">
		<db-attribute-pair source="TABLE1_ID" target="TABLE1_ID"/>
	</db-relationship>
	<db-relationship name="table3" source="MT_TABLE2" target="MT_TABLE3" toMany="false">
		<db-attribute-pair source="TABLE3_ID" target="TABLE3_ID"/>
	</db-relationship>
	<db-relationship name="table2Array" source="MT_TABLE3" target="MT_TABLE2" toMany="true">
		<db-attribute-pair source="TABLE3_ID" target="TABLE3_ID"/>
	</db-relationship>
	<db-relationship name="joins" source="MT_TABLE4" target="MT_JOIN45" toDependentPK="true" toMany="true">
		<db-attribute-pair source="ID" target="TABLE4_ID"/>
	</db-relationship>
	<db-relationship name="joins" source="MT_TABLE5" target="MT_JOIN45" toMany="true">
		<db-attribute-pair source="ID" target="TABLE5_ID"/>
	</db-relationship>
	<obj-relationship name="table2Array" source="MtTable1" target="MtTable2" db-relationship-path="table2Array"/>
	<obj-relationship name="table1" source="MtTable2" target="MtTable1" db-relationship-path="table1"/>
	<obj-relationship name="table3" source="MtTable2" target="MtTable3" deleteRule="Nullify" db-relationship-path="table3"/>
	<obj-relationship name="table2Array" source="MtTable3" target="MtTable2" deleteRule="Deny" db-relationship-path="table2Array"/>
	<obj-relationship name="table5s" source="MtTable4" target="MtTable5" db-relationship-path="joins.toTable5"/>
	<obj-relationship name="table4s" source="MtTable5" target="MtTable4" db-relationship-path="joins.toTable4"/>
	<query name="AllMtTable1" type="SelectQuery" root="obj-entity" root-name="MtTable1">
	</query>
	<query name="MtQueryWithLocalCache" type="SelectQuery" root="obj-entity" root-name="MtTable1">
		<property name="cayenne.GenericSelectQuery.cacheStrategy" value="LOCAL_CACHE"/>
	</query>
	<query name="ParameterizedEJBQLMtQuery" type="EJBQLQuery">
		<property name="cayenne.GenericSelectQuery.cacheStrategy" value="LOCAL_CACHE"/>
		<ejbql><![CDATA[select a from MtTable1 a where a.globalAttribute1 = :g]]></ejbql>
	</query>
	<query name="ParameterizedMtQueryWithLocalCache" type="SelectQuery" root="obj-entity" root-name="MtTable1">
		<property name="cayenne.GenericSelectQuery.cacheStrategy" value="LOCAL_CACHE"/>
		<qualifier><![CDATA[globalAttribute1 = $g]]></qualifier>
	</query>
</data-map>

=== apache/cayenne/cayenne-server/src/test/resources/enum.map.xml
<?xml version="1.0" encoding="utf-8"?>
<data-map xmlns="http://cayenne.apache.org/schema/8/modelMap"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://cayenne.apache.org/schema/8/modelMap http://cayenne.apache.org/schema/8/modelMap.xsd"
          project-version="8">
    <property name="defaultPackage" value="org.apache.cayenne.testdo.enum"/>
    <property name="defaultSuperclass" value="org.apache.cayenne.CayenneDataObject"/>
    <property name="clientSupported" value="true"/>
    <property name="defaultClientPackage" value="test.client"/>
    <property name="defaultClientSuperclass" value="org.apache.cayenne.PersistentObject"/>
    <db-entity name="ENUM_ENTITY">
        <db-attribute name="ENUM_ATTRIBUTE" type="VARCHAR" length="250"/>
        <db-attribute name="ID" type="INTEGER" isPrimaryKey="true" isMandatory="true"/>
    </db-entity>
    <obj-entity name="EnumEntity" className="org.apache.cayenne.testdo.enum_test.EnumEntity" dbEntityName="ENUM_ENTITY">
        <obj-attribute name="enumAttribute" type="org.apache.cayenne.testdo.enum_test.Enum1" db-attribute-path="ENUM_ATTRIBUTE"/>
    </obj-entity>
</data-map>

=== apache/cayenne/cayenne-server/src/test/resources/relationships-many-to-many-join.map.xml
<?xml version="1.0" encoding="utf-8"?>
<data-map xmlns="http://cayenne.apache.org/schema/10/modelMap"
	 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	 xsi:schemaLocation="http://cayenne.apache.org/schema/10/modelMap https://cayenne.apache.org/schema/10/modelMap.xsd"
	 project-version="10">
	<property name="defaultPackage" value="org.apache.cayenne.testdo.relationships_many_to_many_join"/>
	<db-entity name="X_AUTHOR">
		<db-attribute name="AUTHOR_ID" type="INTEGER" isPrimaryKey="true" isMandatory="true"/>
		<db-attribute name="AUTHOR_NAME" type="VARCHAR" isMandatory="true" length="50"/>
	</db-entity>
	<db-entity name="X_SONG">
		<db-attribute name="SONG_ID" type="INTEGER" isPrimaryKey="true" isMandatory="true"/>
		<db-attribute name="SONG_NAME" type="VARCHAR" isMandatory="true" length="50"/>
	</db-entity>
	<db-entity name="X_SONGAUTHOR">
		<db-attribute name="AUTHOR_ID" type="INTEGER" isPrimaryKey="true" isMandatory="true"/>
		<db-attribute name="SONG_ID" type="INTEGER" isPrimaryKey="true" isMandatory="true"/>
	</db-entity>
	<obj-entity name="Author" className="org.apache.cayenne.testdo.relationships_many_to_many_join.Author" dbEntityName="X_AUTHOR">
		<obj-attribute name="name" type="java.lang.String" db-attribute-path="AUTHOR_NAME"/>
	</obj-entity>
	<obj-entity name="Song" className="org.apache.cayenne.testdo.relationships_many_to_many_join.Song" dbEntityName="X_SONG">
		<obj-attribute name="name" type="java.lang.String" db-attribute-path="SONG_NAME"/>
	</obj-entity>
	<db-relationship name="songAuthor" source="X_AUTHOR" target="X_SONGAUTHOR" toDependentPK="true" toMany="true">
		<db-attribute-pair source="AUTHOR_ID" target="AUTHOR_ID"/>
	</db-relationship>
	<db-relationship name="songAuthor" source="X_SONG" target="X_SONGAUTHOR" toDependentPK="true" toMany="true">
		<db-attribute-pair source="SONG_ID" target="SONG_ID"/>
	</db-relationship>
	<db-relationship name="song" source="X_SONGAUTHOR" target="X_SONG">
		<db-attribute-pair source="SONG_ID" target="SONG_ID"/>
	</db-relationship>
	<db-relationship name="author" source="X_SONGAUTHOR" target="X_AUTHOR">
		<db-attribute-pair source="AUTHOR_ID" target="AUTHOR_ID"/>
	</db-relationship>
	<obj-relationship name="authors" source="Song" target="Author" collection-type="java.util.Set" deleteRule="Cascade" db-relationship-path="songAuthor.author"/>
</data-map>

=== apache/cayenne/cayenne/src/test/resources/array-type.map.xml
<?xml version="1.0" encoding="utf-8"?>
<data-map xmlns="http://cayenne.apache.org/schema/11/modelMap"
	 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	 xsi:schemaLocation="http://cayenne.apache.org/schema/11/modelMap https://cayenne.apache.org/schema/11/modelMap.xsd"
	 project-version="11">
	<property name="defaultPackage" value="org.apache.cayenne.testdo.array_type"/>
	<property name="defaultSuperclass" value="org.apache.cayenne.GenericPersistentObject"/>
	<db-entity name="ARRAY_TEST">
		<db-attribute name="DOUBLE_ARRAY" type="VARBINARY" length="1024"/>
		<db-attribute name="ID" type="INTEGER" isPrimaryKey="true" isMandatory="true"/>
	</db-entity>
	<obj-entity name="ArrayTestEntity" className="org.apache.cayenne.testdo.array_type.ArrayTestEntity" dbEntityName="ARRAY_TEST">
		<obj-attribute name="doubleArray" type="java.lang.Double[]" db-attribute-path="DOUBLE_ARRAY"/>
	</obj-entity>
</data-map>

=== apache/cayenne/maven-plugins/cayenne-maven-plugin/src/test/resources/org/apache/cayenne/tools/dbimport/testPreserveCustomObjMappings.map.xml
<?xml version="1.0" encoding="utf-8"?>
<!--
	Licensed to the Apache Software Foundation (ASF) under one
	or more contributor license agreements.  See the NOTICE file
	distributed with this work for additional information
	regarding copyright ownership.  The ASF licenses this file
	to you under the Apache License, Version 2.0 (the
	"License"); you may not use this file except in compliance
	with the License.  You may obtain a copy of the License at

	https://www.apache.org/licenses/LICENSE-2.0

	Unless required by applicable law or agreed to in writing,
	software distributed under the License is distributed on an
	"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
	KIND, either express or implied.  See the License for the
	specific language governing permissions and limitations
	under the License.
-->
<data-map xmlns="http://cayenne.apache.org/schema/10/modelMap"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://cayenne.apache.org/schema/10/modelMap http://cayenne.apache.org/schema/10/modelMap.xsd"
          project-version="10">
    <property name="defaultSchema" value="SCHEMA_01"/>
    <db-entity name="PARENT" schema="SCHEMA_01">
        <db-attribute name="COL2" type="CHAR" length="25"/>
        <db-attribute name="COL3" type="DECIMAL" length="10" scale="2"/>
        <db-attribute name="ID" type="INTEGER" isPrimaryKey="true" isMandatory="true" length="10"/>
    </db-entity>
    <obj-entity name="Parent" className="Parent" dbEntityName="PARENT">
        <obj-attribute name="col2" type="java.lang.String" db-attribute-path="COL2"/>
        <info:property xmlns:info="http://cayenne.apache.org/schema/10/info" name="comment" value="test"/>
    </obj-entity>
</data-map>
